import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve('docs');
const port = 4324;
const types = { '.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.txt':'text/plain' };
const server = http.createServer((req,res)=>{let u=decodeURIComponent((req.url??'/').split('?')[0]);if(u.startsWith('/paint.svelte'))u=u.slice(13)||'/';let f=path.join(root,u);if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(root,'index.html');if(!fs.existsSync(f)){res.writeHead(404).end('nf');return;}res.writeHead(200,{'content-type':types[path.extname(f)]??'application/octet-stream'});fs.createReadStream(f).pipe(res);});
await new Promise(r=>server.listen(port,'127.0.0.1',r));
const puppeteer=(await import('puppeteer-core')).default;
const browser=await puppeteer.launch({executablePath:'C://Program Files\\Google\\Chrome\\Application\\chrome.exe',headless:'new',args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage();
await page.setViewport({width:1600,height:950});
await page.goto(`http://127.0.0.1:${port}/paint.svelte/`,{waitUntil:'networkidle2'});
await new Promise(r=>setTimeout(r,2000));
const clicked = await page.evaluate(() => {
  const els = [...document.querySelectorAll('button')];
  const b = els.find(e => e.textContent.trim() === 'Effects');
  if (!b) return 'no Effects button';
  b.click();
  return 'clicked';
});
await new Promise(r=>setTimeout(r,600));
const menu = await page.evaluate(() => {
  const els = [...document.querySelectorAll('[role="menu"], [role="menuitem"], .menu')]; 
  return document.body.innerText.slice(0, 2000);
});
console.log(clicked);
console.log(menu);
await page.screenshot({path:'.workbuddy-ai/shot-effects.png'});
await browser.close(); server.close();
